config/routes.rb
Maharjan::Application.routes.draw do

  resources :tasks do
    collection do
      get 'deleted'
      get 'completed'
    end
  end
  resources :likes
  resources :stats

  get "error/nocheese4u"
  get "users/new"

  match '/home' => 'home#index'
  match '/' => 'home#index'
  match '/about' => 'home#about'
  match '/contact' => 'home#contact'
  match '/stats' => 'stats#index'
  get "home/index"
  
  resources :sessions, :only => [:new, :create, :destroy]
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match '/signout', to: 'sessions#destroy'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  
  resources :users

  mount MaharjanMailer::Preview => 'preview_email'

  root :to => "home#index"

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :completed_at, :headline, :is_completed, :private

  validates :headline, presence: true, length: {minimum: 2, maximum: 100}

  belongs_to :user
  has_many :like

  before_update :update_comepleted_time
  before_save :update_comepleted_time

  def update_comepleted_time
  	if is_completed && completed_at.nil?
  		self.completed_at = Time.now
  	end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :require_login , :only => [:index, :show, :new, :edit, :create, :update]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.find_all_by_user_id_and_is_deleted(current_user.id, false, :order => "created_at DESC")
    get_stats
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  def deleted
    @tasks = Task.find_all_by_user_id_and_is_deleted(current_user.id, true, :order => "created_at DESC")
    get_stats
    respond_to do |format|
      format.html
      format.json { render json: @tasks }
    end
  end

  def completed
    @tasks = Task.find_all_by_user_id_and_is_completed(current_user.id, true, :order => "created_at DESC")
    get_stats
    respond_to do |format|
      format.html
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])
    @task.user = current_user
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])
    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.is_deleted = true

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully deleted.' }
        format.json { render json: @task, status: :ok, location: @task }
      else
        format.html { render action: "show" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def get_stats
      @alltasks = Task.find_all_by_user_id_and_is_deleted(current_user.id, false, :order => "created_at DESC").length
      @completed = Task.find_all_by_user_id_and_is_completed(current_user.id, true).length
      @deleted = Task.find_all_by_user_id_and_is_deleted(current_user.id, true).length
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.haml
= form_for(@task) do |f|
  - if @task.errors.any?
    #error_explanation
      %ul
        - @task.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :task
    = f.text_field :headline
  .field
    = f.label :done
    = f.check_box :is_completed
  .actions
    = f.submit

app/views/tasks/_sidebar.html.haml
.span2.sidebar
  .created
    = link_to "Tasks", tasks_path
    %br/
    %span.line-heart-pictos.iconic-blue-layers_32x28
    %span.count
      = @alltasks
  .completed
    = link_to "Completed", completed_tasks_path
    %br/
    %span.line-heart-pictos.iconic-blue-check_alt_32x32
    %span.count
      = @completed
  .deleted
    = link_to "Deleted", deleted_tasks_path
    %br/
    %span.line-heart-pictos.iconic-blue-trash_fill_32x32
    %span.count
      = @deleted

app/views/tasks/_singletask.html.haml
.task{:id => "task_#{task.id}"}
  .details
    %p
      = link_to task.headline, task

    = link_to '', :href => "#like",  :id => "task_link_#{task.id}", "data-remote" => true, :onclick => "taskrat.liketask(#{task.id})", :class => "line-heart-pictos.iconic-blue-heart_fill_16x14" do
      - if task.like.count > 0
        %span.line-heart-pictos.iconic-blue-heart_fill_16x14
      - else
        %span.line-heart-pictos.iconic-blue-heart_stroke_16x14

    %span.likecounter= task.like.count > 0 ? task.like.count : ""
    - if !task.completed_at.nil?
      %span.dot .
      Completed:
      = time_ago_in_words(task.completed_at)
      ago
      %span.line-pictos.iconic-blue-check_alt_16x16

  .action
    = link_to '', edit_task_path(task), :class => "link-pictos iconic-blue-pen_16x16", title: "Edit"
    = link_to '', :href => "#delete", :id => "delete_link_#{task.id}", "data-remote" => true, :onclick => "taskrat.deletetask(#{task.id})",  title: "Delete" do
      %span.link-pictos.iconic-blue-x_alt_16x16
    -#= link_to '', task, :id => "task_link_#{task.id}", class: "link-pictos iconic-blue-x_alt_16x16", remote: true,  method: :delete, data: { confirm: 'Are you sure?' }, title: "Delete"

  .createdat
    = time_ago_in_words(task.created_at)
    ago

app/views/tasks/completed.html.haml
.span10.completed
  %h2.task-header Completed Tasks

  -@tasks.group_by {|t| t.created_at.at_beginning_of_day}.each do |created_at, tasks|
    %h3.date-header
      = created_at.strftime("%b %d, %Y %A")
      %span.number-circle= tasks.count

    - tasks.each do |task|
      = render :partial => 'singletask', :locals => { :task => task }

= render :partial => 'sidebar'

app/views/tasks/deleted.html.haml
.span10.deleted
  %h2.task-header Deleted Tasks

  -@tasks.group_by {|t| t.created_at.at_beginning_of_day}.each do |created_at, tasks|
    %h3.date-header
      = created_at.strftime("%b %d, %Y %A")
      %span.number-circle= tasks.count

    - tasks.each do |task|
      = render :partial => 'singletask', :locals => { :task => task }

= render :partial => 'sidebar'

app/views/tasks/edit.html.haml
%h2 Edit task
%br
= render 'form'

app/views/tasks/index.html.haml
.span10
  %h2.task-header Recent Tasks

  -@tasks.group_by {|t| t.created_at.at_beginning_of_day}.each do |created_at, tasks|
    %h3.date-header
      = created_at.strftime("%b %d, %Y %A")
      %span.number-circle= tasks.count

    - tasks.each do |task|
      - if !task.is_deleted
        .task{:id => "task_#{task.id}"}
          .details
            %p
              = link_to task.headline, task

            = link_to '', :href => "#like",  :id => "task_link_#{task.id}", "data-remote" => true, :onclick => "taskrat.liketask(#{task.id})", :class => "line-heart-pictos.iconic-blue-heart_fill_16x14" do
              - if task.like.count > 0
                %span.line-heart-pictos.iconic-blue-heart_fill_16x14
              - else
                %span.line-heart-pictos.iconic-blue-heart_stroke_16x14

            %span.likecounter= task.like.count > 0 ? task.like.count : ""
            - if !task.completed_at.nil?
              %span.dot .
              Completed:
              = time_ago_in_words(task.completed_at)
              ago
              %span.line-pictos.iconic-blue-check_alt_16x16

          .action
            = link_to '', edit_task_path(task), :class => "link-pictos iconic-blue-pen_16x16", title: "Edit"
            = link_to '', :href => "#delete", :id => "delete_link_#{task.id}", "data-remote" => true, :onclick => "taskrat.deletetask(#{task.id})",  title: "Delete" do
              %span.link-pictos.iconic-blue-x_alt_16x16
            -#= link_to '', task, :id => "task_link_#{task.id}", class: "link-pictos iconic-blue-x_alt_16x16", remote: true,  method: :delete, data: { confirm: 'Are you sure?' }, title: "Delete"

          .createdat
            = time_ago_in_words(task.created_at)
            ago

.span2.sidebar
  .created
    = link_to "Tasks", tasks_path
    %br/
    %span.line-heart-pictos.iconic-blue-layers_32x28
    %span.count
      = @tasks.length
  .completed
    = link_to "Completed", tasks_path
    %br/
    %span.line-heart-pictos.iconic-blue-check_alt_32x32
    %span.count
      = @completed.count
  .deleted
    = link_to "Deleted", tasks_path
    %br/
    %span.line-heart-pictos.iconic-blue-trash_fill_32x32
    %span.count
      = @deleted.count

app/views/tasks/new.html.haml
%h2 Add New Task
%br
= render 'form'

app/views/tasks/show.html.haml
%h2 Task Details

%p
  %b Description:
  = @task.headline
%p
  %b Created at:
  = @task.created_at
- if !@task.completed_at.nil?
  %p
    %b Completed at:
    = @task.completed_at
- if @task.is_deleted
  %span.label.important
    Deleted.
  No further updates can be made.
- else
  .action
    = link_to '', edit_task_path(@task), :class => "link-pictos iconic-blue-pen_16x16", title: "Edit"