config/routes.rb
Maharjan::Application.routes.draw do

  resources :tasks do
    collection do
      get 'deleted'
      get 'completed'
    end
  end
  resources :likes
  resources :stats

  get "error/nocheese4u"
  get "users/new"

  match '/home' => 'home#index'
  match '/' => 'home#index'
  match '/about' => 'home#about'
  match '/contact' => 'home#contact'
  match '/stats' => 'stats#index'
  get "home/index"
  
  resources :sessions, :only => [:new, :create, :destroy]
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match '/signout', to: 'sessions#destroy'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  
  resources :users

  mount MaharjanMailer::Preview => 'preview_email'

  root :to => "home#index"

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Taskrat
    = favicon_link_tag 'rat.png'
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js'
    = csrf_meta_tag
  %body
    .topbar
      .fill
        .container
          %a.brand{:href => "/"}
            %span.logo
          - if current_user
            %ul.nav
              %li{:class => ('active' if current_page?(tasks_path))}
                %a{:href => tasks_path, :class => "pictos iconic-blue-home_32x32"}
              %li{:class => ('active' if current_page?(new_task_path))}
                %a{:href => new_task_path, :class => "pictos iconic-blue-plus_alt_32x32"}
              %li{:class => ('active' if current_page?(stats_path))}
                %a{:href => stats_path, :class => "pictos iconic-blue-bars_alt_28x32"}
          #user_nav
            - if current_user
              = succeed " " do
                %span.iconic-blue-bell
                %strong
                  = link_to current_user.name, current_user
              |
              = link_to "  Sign out", signout_path, id: "sign_out"
            - else
              = link_to image_tag('facebookConnect.png'), "/auth/facebook", id: "sign_in"
              |
              = link_to "Log in", signin_path
              
    
    .container{:style=>"width:820px; margin:0 auto;"}
      .content
        .hero-unit
          - flash.each do |name, msg|
            = content_tag :div, msg, :id => "flash_#{name}", :class => "alert-message"
          = yield
    
    %footer
      %h5 © TaskRat 2013
      %ul
        %li.active
          %a{:href => "/", :class => "pictos iconic-blue-home_16x16", :title => "Home"} Home
        %li
          %a{:href => "/about", :class => "pictos iconic-blue-user_12x16", :title => "About"} About
        %li
          %a{:href => "/contact", :class => "pictos iconic-blue-at_16x16", :title => "Contact"} Contact
      

app/views/layouts/welcome_email.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title *|MC:SUBJECT|*
    :css
      #outlook a{
        padding:0;
      }
      body{
        width:100% !important;
      }
      .ReadMsgBody{
        width:100%;
      }
      .ExternalClass{
        width:100%;
      }
      body{
        -webkit-text-size-adjust:none;
      }
      body{
        margin:0;
        padding:0;
      }
      img{
        border:0;
        height:auto;
        line-height:100%;
        outline:none;
        text-decoration:none;
      }
      table td{
        border-collapse:collapse;
      }
      #bodyTable{
        height:100% !important;
        margin:0;
        padding:0;
        width:100% !important;
      }
      h1{
        /*@editable*/color:#202020;
        display:block;
        /*@editable*/font-family:Helvetica;
        /*@editable*/font-size:36px;
        /*@editable*/font-style:normal;
        /*@editable*/font-weight:bold;
        /*@editable*/line-height:100%;
        /*@editable*/letter-spacing:normal;
        margin-top:0;
        margin-right:0;
        margin-bottom:10px;
        margin-left:0;
        /*@editable*/text-align:left;
      }
      h2{
        /*@editable*/color:#404040;
        display:block;
        /*@editable*/font-family:Helvetica;
        /*@editable*/font-size:20px;
        /*@editable*/font-style:normal;
        /*@editable*/font-weight:bold;
        /*@editable*/line-height:100%;
        /*@editable*/letter-spacing:normal;
        margin-top:0;
        margin-right:0;
        margin-bottom:10px;
        margin-left:0;
        /*@editable*/text-align:left;
      }
      h3{
        /*@editable*/color:#606060;
        display:block;
        /*@editable*/font-family:Helvetica;
        /*@editable*/font-size:16px;
        /*@editable*/font-style:normal;
        /*@editable*/font-weight:bold;
        /*@editable*/line-height:100%;
        /*@editable*/letter-spacing:normal;
        margin-top:0;
        margin-right:0;
        margin-bottom:10px;
        margin-left:0;
        /*@editable*/text-align:left;
      }
      h4{
        /*@editable*/color:#808080;
        display:block;
        /*@editable*/font-family:Helvetica;
        /*@editable*/font-size:12px;
        /*@editable*/font-style:normal;
        /*@editable*/font-weight:bold;
        /*@editable*/line-height:100%;
        /*@editable*/letter-spacing:normal;
        margin-top:0;
        margin-right:0;
        margin-bottom:10px;
        margin-left:0;
        /*@editable*/text-align:left;
      }
      #templatePreheader{
        /*@editable*/background-color:#000000;
        /*@editable*/border-bottom:0;
      }
      .preheaderContent{
        /*@editable*/color:#FFFFFF;
        /*@editable*/font-family:Helvetica;
        /*@editable*/font-size:10px;
        /*@editable*/line-height:125%;
        /*@editable*/text-align:left;
      }
      .preheaderContent a:link,.preheaderContent a:visited,.preheaderContent a .yshortcuts {
        /*@editable*/color:#E60101;
        /*@editable*/font-weight:normal;
        /*@editable*/text-decoration:underline;
      }
      #templateHeader{
        /*@editable*/background-color:#F4F4F4;
        /*@editable*/border-top:0;
        /*@editable*/border-bottom:0;
      }
      .headerContent{
        /*@editable*/color:#505050;
        /*@editable*/font-family:Helvetica;
        /*@editable*/font-size:20px;
        /*@editable*/font-weight:bold;
        /*@editable*/line-height:100%;
        /*@editable*/padding-top:0;
        /*@editable*/padding-right:0;
        /*@editable*/padding-bottom:0;
        /*@editable*/padding-left:0;
        /*@editable*/text-align:left;
        /*@editable*/vertical-align:middle;
      }
      .headerContent a:link,.headerContent a:visited,.headerContent a .yshortcuts {
        /*@editable*/color:#EB4102;
        /*@editable*/font-weight:normal;
        /*@editable*/text-decoration:underline;
      }
      #headerImage{
        height:auto;
        max-width:600px !important;
      }
      .templateBody{
        /*@editable*/background-color:#F4F4F4;
      }
      .bodyContent{
        /*@editable*/color:#505050;
        /*@editable*/font-family:Helvetica;
        /*@editable*/font-size:13px;
        /*@editable*/line-height:150%;
        /*@editable*/text-align:left;
      }
      .bodyContent a:link,.bodyContent a:visited,.bodyContent a .yshortcuts {
        /*@editable*/color:#D00000;
        /*@editable*/font-weight:normal;
        /*@editable*/text-decoration:underline;
      }
      .contentTitleBar h1,.contentTitleBar h2,.contentTitleBar h3,.contentTitleBar h4{
        line-height:100% !important;
        margin:0 !important;
      }
      .bodyContent img{
        display:inline;
        height:auto;
      }
      #templateFooter{
        /*@editable*/border-top:0;
      }
      body,#bodyTable{
        /*@editable*/background-color:#F4F4F4;
      }
      .footerContent{
        /*@editable*/color:#808080;
        /*@editable*/font-family:Helvetica;
        /*@editable*/font-size:10px;
        /*@editable*/line-height:150%;
        /*@editable*/text-align:left;
      }
      .footerContent a:link,.footerContent a:visited,.footerContent a .yshortcuts {
        /*@editable*/color:#606060;
        /*@editable*/font-weight:normal;
        /*@editable*/text-decoration:underline;
      }
      .footerContent img{
        display:inline;
      }
  %body{:leftmargin => "0", :marginheight => "0", :marginwidth => "0", :offset => "0", :topmargin => "0"}
    %center
      %table#bodyTable{:border => "0", :cellpadding => "0", :cellspacing => "0", :height => "100%", :width => "100%"}
        %tr
          %td{:align => "center", :valign => "top"}
            / // BEGIN PREHEADER
            %table#templatePreheader{:border => "0", :cellpadding => "10", :cellspacing => "0", :width => "100%"}
              %tr
                %td{:align => "center", :valign => "top"}
                  %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "600"}
                    %tr
                      %td.preheaderContent{:valign => "top"}
                      %td{:width => "20"}
                        %br/
                      %td.preheaderContent{:valign => "top", :width => "200"}

            %table#templateContainer{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
              %tr
                %td{:align => "center", :valign => "top"}
                  / // BEGIN HEADER
                  %table#templateHeader{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
                    %tr
                      %td{:align => "center", :valign => "top"}
                        %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "600"}
                          %tr
                            %td.headerContent
                              = link_to image_tag('http://protected-cliffs-4995.herokuapp.com/assets/rat.png', :id => "headerImage campaign-icon", :style => "max-width:600px; display: inline-block; vertical-align: bottom;"),  "#{@url}"
                              %h1{:style => "display: inline-block; vertical-align: bottom;"}
                                = link_to 'TaskRat', "#{@url}", :style => "text-decoration: none;color: #202020; font-weight: 600;"
                  / END HEADER \\
              %tr
                %td{:align => "center", :valign => "top"}
                  / // BEGIN BODY
                  %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
                    %tr
                      %td.templateBody{:align => "center", :valign => "top"}
                        %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "600"}
                          %tr
                            %td.bodyContent{ :style => "padding-bottom:20px;", :valign => "top"}
                          %tr
                            %td.bodyContentBlock{:align => "center", :style => "padding-top:30px; border-top: 1px solid #CCC;", :valign => "top"}
                              %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
                                %tr
                                  %td.bodyContent{:colspan => "3",  :style => "padding-bottom:10px;", :valign => "top"}
                                    %h2 Welcome #{@user.name}
                                %tr
                                  %td.bodyContent{:style => "padding-bottom:30px; font-size: 16px;", :valign => "top"}
                                    You have successfully signed up to
                                    = link_to 'TaskRat', "#{@url}"
                                    %br/
                                    Your username is: #{@user.email}
                                    %br/
                                    %br/
                                    Rat that Task and feel productive by completing it.
              %tr
                %td{:align => "center", :valign => "top"}
                  / // BEGIN FOOTER
                  %table#templateFooter{:border => "0", :cellpadding => "40", :cellspacing => "0", :width => "100%"}
                    %tr
                      %td{:align => "center", :style => "padding-bottom:40px;", :valign => "top"}
                        %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "600"}
                          %tr
                            %td.footerContent{:colspan => "3", :style => "padding-bottom:20px;", :valign => "top"}
                              = link_to image_tag('http://protected-cliffs-4995.herokuapp.com/assets/glyphicons/glyphicons_410_facebook.png', :id => "social-icon", :style => "display: inline-block; vertical-align: bottom; margin-right: 10px;"),  "http://www.facebook.com/chinny.maharjan"
                              = link_to image_tag('http://protected-cliffs-4995.herokuapp.com/assets/glyphicons/glyphicons_411_twitter.png', :id => "social-icon", :style => "display: inline-block; vertical-align: bottom; margin-right: 10px;"),  "http://www.twitter.com/sachinmaharjan"
                              = link_to image_tag('http://protected-cliffs-4995.herokuapp.com/assets/glyphicons/glyphicons_380_pinterest.png', :id => "social-icon", :style => "display: inline-block; vertical-align: bottom; margin-right: 10px;"),  "#"
                          %tr
                            %td.footerContent{:valign => "top", :style => "font-size: 13px;"}
                              %em Copyright © 2013, All rights reserved.
                              %br/
                              = link_to 'TaskRat', "#{@url}"
                              %br/
                              %br/
                              %br/
                            %td{:width => "20"}
                              %br/
                            %td#monkeyRewards.footerContent{:valign => "top", :width => "200"}

app/views/layouts/welcome_email_bkp.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
  %body
    %h1
      Welcome #{@user.name}
    %p
      You have successfully signed up to #{@url}.
      %br/
      Your username is: #{@user.email}.
      %br/
    %p
      To login to the site, just follow this link: #{@url}.
    %p Thanks for joining and have a great day!